### ISSUE TITLE
[FEATURE] Packwiz Based modpack Support

### ISSUE THREAD

**Issue by Merith-TK** [QuestCraftPlusPlus/QuestCraft#513]
### 🛠️ Describe the solution you'd like

this would make it easier to allow for customized modpacks to be shared, and could *in theory* be integrated into the profile switcher!

Currently the only launcher that supports packwiz is MultiMC Variants due to the ability to run an "pre-launch" command, however I could see Packwiz being integrated into Questcraft

here is an "template" i made for modpacks that use packwiz, it can export to Curseforge, Modrinth, Technic, and MultiMC
https://github.com/Merith-TK/modpack-template

how packwiz works is you place the `packwiz-bootstrap-installer.jar` into your CurrentWorkingDirectory (`.minecraft`) and then run
`"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://gitlab.com/Merith-TK/modpack-template/-/raw/main/.minecraft/pack.toml`

and this is the contents of `pack.toml` which would make it easy to parse and show per instance, as well as manage versions
```toml
name = "Modpack Template"
author = "Merith.TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ab22d665a56d4ba026899210762e6bf3641be4f35fe8d56ffd4e2ed3d191114"

[versions]
fabric = "0.14.9"
minecraft = "1.19.4"
```

index.toml is an index of all files fetched by packwiz, 

```toml
hash-format = "sha256"

[[files]]
file = "bin/version.json"
hash = "b5f8dc11af2e5d2eeb17007a53fced417fdb3020baac8a8f8dd230a2d3fd854e"

[[files]]
file = "modpack.icon.png"
hash = "50f74a7debb4a852e1384434500515f2478b8dcf0d71b75eba148ca34d89715c"

[[files]]
file = "mods/lithium.pw.toml"
hash = "be8427f766253fce639d6e3e351b726a9b98e6ebc3ed4bec2023ea352bda0ae8"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "869cfbeecb3595d8e72a7ec77741389e9b2154d63478ac3ecb1fcaa0879c80ec"
metafile = true

[[files]]
file = "mods/phosphor.pw.toml"
hash = "466d5892937df5aa05388291463b163b42fa454d8bfd22713484a0167ca3702d"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "103f9e1bc20ebbef5a496b73572aaa9a24066831fc61fe3a28eedea3602153f9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "942e9738be0c83d196cd7cee9a3e93b9184faff7882d83e3d52ec66912ac07eb"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "4aba93a705eb2c6300818297bc1d85329b9b085392810dbf15c79b5e3dd6d0ef"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"
```

the `metafile` tag shows that it is a metadata file pointing to an mod on an hosting provider (these can be directly linked to URLS and not just Curse or Modrinth)
```toml
name = "Sodium"
filename = "sodium-fabric-mc1.19.4-0.4.11+build.26.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/AANobbMI/versions/ugiIczl5/sodium-fabric-mc1.19.4-0.4.11%2Bbuild.26.jar"
hash-format = "sha1"
hash = "db1f37c03a674a5f01132f5a3bb8fb6361c9dca8"

[update]
[update.modrinth]
mod-id = "AANobbMI"
version = "ugiIczl5"
```

### 🤔 Describe alternatives you've considered

Manual File Transfer has always been... *extremely finicky* for me, after breaking quest craft *multiple times* as there is no clean way to transfer files
